import {
    faSun,
    faCloudSun,
    faCloud,
    faSmog,
    faCloudSunRain,
    faCloudRain as light_rain,
    faCloudShowersHeavy as moderate_rain,
    faCloudShowersWater as heavy_rain,
    faSnowflake,
    faCloudMeatball,
    faCloudBolt
} from '@fortawesome/free-solid-svg-icons'

// Duzo ikon sie powtarza. W darmowej wersji jest tylko 40 ikon dotyczacych pogody.
export const CodeDefinitions = {
    0: faSun,
    1: faCloudSun,
    2: faCloudSun,
    3: faCloud,
    45: faSmog,
    48: faSmog,
    51: faCloudSunRain,
    53: faCloudSunRain,
    55: faCloudSunRain,
    56: light_rain,
    57: heavy_rain,
    61: light_rain,
    63: moderate_rain,
    65: heavy_rain,
    66: light_rain,
    67: heavy_rain,
    71: faSnowflake,
    73: faSnowflake,
    75: faSnowflake,
    77: faCloudMeatball,
    80: light_rain,
    81: moderate_rain,
    82: heavy_rain,
    85: faSnowflake,
    86: faCloudMeatball,
    95: faCloudBolt,
    96: faCloudBolt,
    99: faCloudBolt
}